#!/usr/bin/env bash

# deephash by pathawks
# Source: https://github.com/pathawks/deephash
#
# This script is licensed under The MIT License (see LICENSE for more information).

echo "# SHA-256"
find * -type f -print0 | xargs -0 shasum -b -a 256
